// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWPcdxu6NYd2HEsAoyLKrMC2ptcxk6Ifo',
    appId: '1:734910045094:web:f355d6e4d1be24027d4d67',
    messagingSenderId: '734910045094',
    projectId: 'go-study-ub-hub',
    authDomain: 'go-study-ub-hub.firebaseapp.com',
    storageBucket: 'go-study-ub-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJMvVZlmP0HbRo29WKU97qQ8wZSEX1FGg',
    appId: '1:734910045094:android:9f156655cd853bef7d4d67',
    messagingSenderId: '734910045094',
    projectId: 'go-study-ub-hub',
    storageBucket: 'go-study-ub-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7cN6j0FAMqKUua19Zi0pVyFb_nzAVZmM',
    appId: '1:734910045094:ios:699f1e59a6c1ec9b7d4d67',
    messagingSenderId: '734910045094',
    projectId: 'go-study-ub-hub',
    storageBucket: 'go-study-ub-hub.firebasestorage.app',
    iosBundleId: 'com.example.neo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7cN6j0FAMqKUua19Zi0pVyFb_nzAVZmM',
    appId: '1:734910045094:ios:699f1e59a6c1ec9b7d4d67',
    messagingSenderId: '734910045094',
    projectId: 'go-study-ub-hub',
    storageBucket: 'go-study-ub-hub.firebasestorage.app',
    iosBundleId: 'com.example.neo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWPcdxu6NYd2HEsAoyLKrMC2ptcxk6Ifo',
    appId: '1:734910045094:web:2783520e6456658e7d4d67',
    messagingSenderId: '734910045094',
    projectId: 'go-study-ub-hub',
    authDomain: 'go-study-ub-hub.firebaseapp.com',
    storageBucket: 'go-study-ub-hub.firebasestorage.app',
  );

}