// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHGSS8XCQ3EJ74XQ562O9s9mmZZb93i_Y',
    appId: '1:1002439415745:web:897b362af6a9acb5374140',
    messagingSenderId: '1002439415745',
    projectId: 'facultyofscienceapp-neo',
    authDomain: 'facultyofscienceapp-neo.firebaseapp.com',
    storageBucket: 'facultyofscienceapp-neo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_JkBvu6AjB01Wh4Sc3GDnY6iuy-PjQPg',
    appId: '1:1002439415745:android:6474e2eca9769745374140',
    messagingSenderId: '1002439415745',
    projectId: 'facultyofscienceapp-neo',
    storageBucket: 'facultyofscienceapp-neo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEtC729G0fd2F9rn8HrcBVUhkN7lxLDuc',
    appId: '1:1002439415745:ios:f2239d51bb9e2ad4374140',
    messagingSenderId: '1002439415745',
    projectId: 'facultyofscienceapp-neo',
    storageBucket: 'facultyofscienceapp-neo.firebasestorage.app',
    iosBundleId: 'com.example.neo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEtC729G0fd2F9rn8HrcBVUhkN7lxLDuc',
    appId: '1:1002439415745:ios:f2239d51bb9e2ad4374140',
    messagingSenderId: '1002439415745',
    projectId: 'facultyofscienceapp-neo',
    storageBucket: 'facultyofscienceapp-neo.firebasestorage.app',
    iosBundleId: 'com.example.neo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHGSS8XCQ3EJ74XQ562O9s9mmZZb93i_Y',
    appId: '1:1002439415745:web:d80f5a22f38793d9374140',
    messagingSenderId: '1002439415745',
    projectId: 'facultyofscienceapp-neo',
    authDomain: 'facultyofscienceapp-neo.firebaseapp.com',
    storageBucket: 'facultyofscienceapp-neo.firebasestorage.app',
  );
}
